export const loadingTypes = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',
}

export const cartTypes = {
  GET_CART: 'GET_CART',
  GET_CARTS: 'GET_CARTS',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART'
}

export const userTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAIL: 'LOGIN_FAIL',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
}

export const types = {
  ADD_USER: 'ADD_USER',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_CATEGORY: 'ADD_CATEGORY',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRODUCTS: 'GET_PRODUCTS',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY'
};

export const reviewTypes = {
  CREATE_REVIEW: 'CREATE_REVIEW',
  GET_REVIEWS: 'GET_REVIEWS'
}